events {
}

http {
    server {
        listen 80;
        server_name www.l2-2.ephec-ti.be;
        root /var/www/html/www;
        index index.html;
    }

    server {
        listen 80;
        server_name blog.l2-2.ephec-ti.be;
        root /var/www/html/blog;
        index index.html;
    }
}
